author: 'juhlinus'

name: 'Easy Coding Standard Github Action'

description: 'A Github Action for simplify/ecs'

inputs:
  files:
    description: 'Which files to run on'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.files }}